# Generated by Django 4.1 on 2022-11-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_games_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
