# Generated by Django 4.1 on 2022-11-13 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_game_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
