# Generated by Django 4.1 on 2022-11-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0004_delete_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_logo', models.ImageField(upload_to='photos')),
                ('game_title', models.CharField(max_length=255)),
                ('game_rating', models.FloatField()),
            ],
        ),
    ]
