# Generated by Django 4.1 on 2022-11-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_server',
            field=models.CharField(default='', max_length=255),
        ),
    ]
