# Generated by Django 4.1 on 2022-11-14 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_game_server'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_server',
            new_name='game_link',
        ),
    ]
