# Generated by Django 4.1 on 2022-11-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_rename_game_server_game_game_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_category',
            field=models.CharField(default='', max_length=255),
        ),
    ]
